### ISSUE TITLE
runRoute incompatible with relative URI's

### ISSUE THREAD

**Issue by RasmusKlett** [ElvishJerricco/servant-router#1]
This took me so stupidly long to figure out!!

runRoute will return FailFatal on any relative URI's, per the behaviour of Network.URI.parseURI. I think the behaviour of parseURI has been changed in network-uri 2.6 or something.

Anyway, this is very problematic, because Reflex.Dom.Contrib.Router.routeSite returns relative URI's, and thus doesn't work with this library.

I think the solution is simply to change runRoute to use parseURIReference instead. There might also need to be a preprocessor check for old versions of nework-uri..?

**Comment by ElvishJerricco** [comment]
Hm my bad. I think the more potent solution would be to allow the user to choose how to parse the URI. This essentially means requiring users to pass the path and query compents already parsed rather than making assumptions about how to parse them.

**Comment by RasmusKlett** [comment]
So just switch to:

``` haskell
 runRoute :: Location -> Proxy layout -> RouteT layout m a -> m a 
```

and let the user convert the string to a URI and then use the provided uriToLocation before passing it to runRoute?

**Comment by ElvishJerricco** [comment]
I think that would be a good solution. Would you agree?

**Comment by RasmusKlett** [comment]
I think I'm actually leaning towards doing the relative parsing by default, and possibly specifying a Location-based version as an extra option. I see these two arguments for doing this:
- My guess is 95% of users will use this with the Contrib routeSite function, and thus will be parsing relative URI's. It doesn't seem useful that everyone needs to specify the same boilerplate parsing from String to Location, when it will almost always be the exact same code.
- The parseURIReference function produces a Maybe indicating failure to parse. This failure should usually be treated in the same way as a failure to match on the Servant API, as done in the example on the frontpage. Forcing the user to handle this error separately again pushes needless boilerplate to the user. 

So all in all, I think runRoute should keep its current type, and be changed to use parseURIReference instead, while an alternate version taking a Location instead of a String could be added for the rare alternative uses of the library.

**Comment by ElvishJerricco** [comment]
Seems reasonable to me. Feel free to send a pull request. Otherwise, I'll try to get on this myself this weekend.

**Comment by RasmusKlett** [comment]
There you go :)
