### ISSUE TITLE
Still not compatible with Reflex

### ISSUE THREAD

**Issue by qrilka** [ElvishJerricco/servant-router#5]
I'm wondering why #4 was closed when example from README still doesn't work properly

**Comment by ElvishJerricco** [comment]
Sorry, didn't get around to answering you in the other thread. This code (copied almost exactly from the README) compiles fine for me:

``` haskell
{-# LANGUAGE DataKinds     #-}
{-# LANGUAGE TypeOperators #-}

module Main where

import           Data.Proxy
import           Reflex.Dom
import           Reflex.Dom.Contrib.Router
import           Servant.API
import           Servant.Router

type MyApi = "books" :> Capture "id" Int :> View
        :<|> "search" :> QueryParam "keywords" String :> View
myApi :: Proxy MyApi
myApi = Proxy

main :: IO ()
-- reflex-dom-contrib provides a 'routeSite' function                                                                                                                                                       
-- for routing single page applications with reflex.                                                                                                                                                        
-- servant-router uses the provided uri String to perform the routing.                                                                                                                                      
main = routeSite $ \uri -> do
  let handler = books :<|> search
      books i = do
        -- Here, you would get and display a book.                                                                                                                                                          
        -- Return a Reflex event for changing the browser location.                                                                                                                                         
        return never
      search Nothing = do
        -- Here, you would display a search bar.                                                                                                                                                            
        return never
      search (Just keywords) = do
        -- Here you would display the search bar plus results.                                                                                                                                              
        return never
  -- With the handler constructed, run the router with the uri.                                                                                                                                             
  result <- runRoute uri myApi handler
  case result of
    -- If 'Left', there was no correct route for the uri.                                                                                                                                                   
    Left _ -> do
      el "div" $ text "No such page"
      return never
    -- If 'Right', the result of the route is returned.                                                                                                                                                     
    Right e -> return e
```

I will be publishing this in a test-suite in the package shortly; maybe tonight.

**Comment by ElvishJerricco** [comment]
Yep, just pushed a commit with the example compiling successfully.

**Comment by ElvishJerricco** [comment]
Looking at the code and error message you posted previously, you forgot to cut out the call to `runExceptT`, since I replaced the usage of `MonadError` with `m (Either ...)`. So you were calling `runExceptT`, plugging `ExceptT ...` in for `m` in `runRoute`, thus binding `Either RoutingError (Event t String)` in where you need `Event t String`.

EDIT: That is, `runRoute` was returning `ExceptT e1 m (Either RoutingError (Event t String))`.

**Comment by qrilka** [comment]
@ElvishJerricco that sounds reasonable but I couldn't compile the example with GHCJS we use because of https://github.com/kazu-yamamoto/logger/issues/97 :(
And your example isn't what I was testing - it doesn't use any reflex functions inside of handler and that was exactly the problem I was pointing at.
So it's good to have a test but it's not cool that it doesn't test real life scenario.

**Comment by ElvishJerricco** [comment]
Wait, so what exactly is the problem then? What does `servant-router` have to do with `kazu-yamamoto/logger`? How does the example not test a real life scenario?

**Comment by qrilka** [comment]
There are 2 separate things:
- I can't build servant-router with GHCJS we use because of that error but that our local problem not of `servant-router`
- Reflextest doesn't use any Reflex in `handler` code where Reflex is suppose to be

And the 2nd point was pointed at in #4:

> example from README with just el "div" $ text "Sample text" added into

**Comment by ElvishJerricco** [comment]
Ah, gotcha! Just threw in a commit adding some calls to reflex within the handlers. Works perfectly =)

**Comment by ElvishJerricco** [comment]
Is this good to close then?

**Comment by qrilka** [comment]
Yeah, thank you @ElvishJerricco

**Comment by qrilka** [comment]
And it compiled well in a separate package with `servant-router` as a dependency.
So no I need to figure out how to integrate it into the app
