### ISSUE TITLE
Any good way to use `safeLink` with servant-router?

### ISSUE THREAD

**Issue by qrilka** [ElvishJerricco/servant-router#6]
I need to render links in my app (as `routeSite` is not "recursive" see https://github.com/reflex-frp/reflex-dom-contrib/issues/19) so currently I use `ViewTransform` but that leads to views being duplicated in routes so I could pass them to `safeLink`.
And it makes me wonder if its possible somehow to make `safeLink` work on `View` directly

**Comment by ElvishJerricco** [comment]
Sorry, I'm not familiar with what `safeLink` is?

**Comment by ElvishJerricco** [comment]
And what do you mean by views being duplicated?

**Comment by qrilka** [comment]
http://hackage.haskell.org/package/servant-0.9.1.1/docs/Servant-Utils-Links.html#v:safeLink is a _safe_ way to render links in Servant :)
Regarding duplication - servant API could be composed from multiple routes like `Route1 :<|> Route2` so e.g. `Route1` (e.g. `"api" :> "books" :> Get '[JSON] [String]` from https://github.com/ElvishJerricco/servant-router/blob/master/test/Server.hs) could be used for route handler definition and for URL construction using `safeLink`.
But when doing similar  Views decomposition I need to have a `View` definition and route definition constructed from it using `ViewTransform`.

**Comment by ElvishJerricco** [comment]
Ah I see. Yea it should be pretty easy to give View a MkLink type family instance. Should be a simple fix.

That said, this also raises a more interesting issue. The app should be capable of rerouting without converting to URL then back. I'll look into this too.

Also, that routeSite bug seems strange. I might take a crack at that too.

**Comment by qrilka** [comment]
But what if I want to show some route just as a link? I.e. to allow user to copy that link into email, messenger or do something else about it - how do you see that possible without rendering that route into HTML?

**Comment by ElvishJerricco** [comment]
Right that's why I want to both fix that problem, AND look into the other thing

**Comment by ElvishJerricco** [comment]
Btw, I also updated `servant-router` to build with lts 7.7, and you might find the `stack.yaml` interesting.

**Comment by qrilka** [comment]
Thanks but actually we're using `lts-7.3` and there were no problems with `servant-router` :)

**Comment by qrilka** [comment]
@ElvishJerricco do you plan to release it on Hackage?

**Comment by ElvishJerricco** [comment]
I didn't write a test suite at all, just tested by hand a little. Could you try out the change directly from GitHub, and if it seems to work, I'll put it on Hackag?

**Comment by qrilka** [comment]
I did it already - it works fine for me

**Comment by qrilka** [comment]
BTW - any plans to create a new library release including this one?

**Comment by qrilka** [comment]
@ElvishJerricco still no new version?
