### ISSUE TITLE
Relax dependency of http-api-data

### ISSUE THREAD

**Issue by tomsmalley** [ElvishJerricco/servant-router#8]
Is there any reason the dependency is so narrow? It prevents building with servant-server > 0.7.1.

**Comment by ElvishJerricco** [comment]
I'm guessing a lot of the constraints probably need to be relaxed. I've got a number of things that I need to do to shape this package up for another release.

**Comment by ElvishJerricco** [comment]
Fixed in ac21bf13c4d3a7f124706583ecd84ee731aac050
